# Generated by Django 6.0.2 on 2026-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_appointment_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
